#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# all padding and gaps
yabai -m config layout bsp
yabai -m config top_padding 25
yabai -m config bottom_padding 30
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 15

# Floating apps
yabai -m rule --add app="^Alacritty$" manage=off border=off 
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^Photos$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Mail$" manage=off
# yabai -m rule --add app="Safari" opacity=1.0
# yabai -m rule --add app="qutebrowser" opacity=1.0

yabai -m config window_border_blur off

# window opacity
yabai -m config window_opacity off 
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.5

# window border seetings
yabai -m config window_border_radius 0
yabai -m config window_border on
yabai -m config window_border_placement exterior
yabai -m config window_border_width 3

# global settings
yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus on 
yabai -m config window_origin_display default 
yabai -m config window_placement second_child 

yabai -m config window_topmost on 
yabai -m config window_shadow float 

yabai -m config insert_feedback_color 0xFFE6EBF1
yabai -m config normal_window_border_color 0xFF2D4059 
yabai -m config active_window_border_color 0xFFE6EBF1 

yabai -m config split_ratio 0.50 
yabai -m config split_type auto 
yabai -m config mouse_modifier fn 
yabai -m config mouse_action1 move 
yabai -m config mouse_action2 resize 
yabai -m config mouse_drop_action swap 

yabai -m config external_bar all:26:0 

# space settings
yabai -m space 1 --label BASE
yabai -m space 2 --label CODE
yabai -m space 3 --label WEB
yabai -m space 4 --label MESSENGER
yabai -m space 5 --label DOCS

echo "yabai configuration loaded.."
